esphome:
  name: gosund-slc-2
  friendly_name: Gosund SLC 2

bk72xx:
  board: generic-bk7231t-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gosund-Slc-2 Fallback Hotspot"
    password: "t4CRdfZUxkeS"

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

# Enable switch for remote restart
switch:
  - platform: restart
    name: "Gosund SLC 2 Restart"

# Example configuration entry
light:
  - platform: rgb
    name: "Gosund SLC 2"
    red: output_red
    green: output_green
    blue: output_blue
    id: led_strip

# Example output entry
output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO26
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO9
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO24

binary_sensor:
  - platform: status
    name: "Gosund SLC 2 - Status"
    device_class: connectivity
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
    name: "Gosund SLC 2 Pushbutton"
    internal: true
    on_press:
      then:
        - light.toggle: led_strip

sensor:
  - platform: wifi_signal
    name: "Gosund SLC 2 - Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "Gosund SLC 2 - Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version
